### ISSUE TITLE
Bottom Taskbar

### ISSUE THREAD

**Issue by sabinabialic** [sabinabialic/mywebsite#5]
At the bottom of the website, create a section with ways to connect/contact me
- All the texts need to redirect the user to the appropriate platform when clicked
- Need to include icons for all the social media platforms (LinkedIn, Github, Email)
- Need to include a link to the source code for this website

**Subtasks**
- [ ] Create a new bottom taskbar widget
- [ ] Get all the appropriate icons for all the social media platforms
- [ ] On click of the text, redirect the user to the appropriate social media website
- [ ] Create a link to the source code for this project

**Example**
![image](https://user-images.githubusercontent.com/27565175/75448124-a33dd300-5938-11ea-8ad8-20155c8297d6.png)
