### ISSUE TITLE
Scroll to a Position on NavBar Click

### ISSUE THREAD

**Issue by sabinabialic** [sabinabialic/mywebsite#6]
Since the website is a portfolio, all the "pages" lie on one screen, thus when the navigation bar elements are clicked, we need to scroll to the corresponding header position (except for view resume)

**Blocked by #GH-3**

**Subtasks**
- [ ] Investigate ListView... https://cogitas.net/scroll-position-flutter-listview/
- [ ] Create "pages" for About, Experience, and Projects
- [ ] On click of the navbar item, scroll the page such that the section header is at the topmost of the screen
